name: Scoreboard
main: Ayzrix\Scoreboard\Main
api: 3.0.0
version: 1.5.2
softdepend:
  - PiggyFactions
  - FactionsPro
  - SimpleFaction
  - EconomyAPI
  - PurePerms
  - SkyBlock
  - SeeDevice
  - Bounty
  - Prisons
  - OnlineTime
  - CombatLogger
  - FightLogger
  - MyPlot
  - CoinsSystem
  - KDR
  - VoteParty
  - BankUI
  - RedSkyBlock
  - VanishV2
  - MultiEconomy
  - RankSystem
  - MultiServerCounter
  - Godmode
author: Ayzrix
