name: Scoreboard
main: Ayzrix\Scoreboard\Main
api: 3.0.2
version: 1.1.0
softdepend:
  - PiggyFactions
  - FactionsPro
  - SimpleFaction
  - EconomyAPI
  - PurePerms
  - SkyBlock
  - SeeDevice
  - Bounty
  - Prisons
  - OnlineTime
  - CombatLogger
  - FightLogger
  - MyPlot
  - CoinsSystem
author: Ayzrix
