---
#     _____                    _                         _
#    / ____|                  | |                       | |
#   | (___   ___ ___  _ __ ___| |__   ___   __ _ _ __ __| |
#    \___ \ / __/ _ \| '__/ _ \ '_ \ / _ \ / _` | '__/ _` |
#    ____) | (_| (_) | | |  __/ |_) | (_) | (_| | | | (_| |
#   |_____/ \___\___/|_|  \___|_.__/ \___/ \__,_|_|  \__,_|
#
#

# Time between a scoreboard update.
# RECOMMANDED: 2 seconds
update_time: 40 # TICKS 20 = 1 second

options:
  # {faction_name} {faction_rank} {faction_power}
  PiggyFaction: false
  # {faction_name} {faction_power}
  FactionsPro: false
  # {faction_name} {faction_rank} {faction_power} {faction_money}
  SimpleFaction: false
  # {money}
  EconomyAPI: false
  # {rank} {prefix} {suffix}
  PurePerms: false
  # {island_blocks} {island_members} {island_rank} {island_size}
  SkyBlock: false
  # {device}
  SeeDevice: false

# BASE VARIABLES : {ping} {tps} {name} {online} {max_online} {level} {x} {y} {z}

per_world: false
title: "ยง6Scoreboard"
lines:
    - "line1"
    - "line2"

# Edit just if per_world is on true
worlds:
  world:
    title: "ยง6Scoreboard"
    lines:
      - "line1"
      - "line2"
...
